### ISSUE TITLE
Linking problem

### ISSUE THREAD

**Issue by goran-mahovlic** [JON95Git/lvgl-rasp-sdl#1]
Hi, thank you for your work!

I am trying to compile your sample as later I would like to use it with Envox LVGL gui builder 

https://github.com/eez-open/studio

on this device that I just created 

https://github.com/intergalaktik/bb3-cm4

I am not able to understand last step https://github.com/JON95Git/lvgl-rasp-sdl#building-the-application-1

Where this should be done, as now I have linking error 

![Screenshot from 2023-11-25 23-42-05](https://github.com/JON95Git/lvgl-rasp-sdl/assets/4248736/e63f5968-0734-410e-9f13-e42c2b286236)

Best, Goran

**Comment by JON95Git** [comment]
Hi @goran-mahovlic 
Thanks for opening the issue.
Well, if I understand correctly, you are not able to link the SDL library, right?
If so, basically you have to:
- Build the SDL library (seems your target is aarch64 not arm right?)
- Copy SDL/ directory to your project directory
- Add the references to SDL into you build system (last step)

Take a look at my Makefile, specially the "SDL" references:
https://github.com/JON95Git/lvgl-rasp-sdl/blob/bd300e74455df00c7557afe14672da5db1651520/Makefile#L17
https://github.com/JON95Git/lvgl-rasp-sdl/blob/bd300e74455df00c7557afe14672da5db1651520/Makefile#L30
https://github.com/JON95Git/lvgl-rasp-sdl/blob/bd300e74455df00c7557afe14672da5db1651520/Makefile#L44

Let me know if you have any question.
Thanks,
Jonathan

**Comment by goran-mahovlic** [comment]
@JON95Git Thank for answering! 

I will try again in coming days. 
As I was not able to get it we have switched to SDL2 app without LVGL that we already have as simulator ( it has turned out this could be even better approach for BB3 )

https://youtu.be/SRumQEken4A?si=n80LIgpGdwoeEP3T

In any way I am still interested in getting this running as some users would probably like to use studio and LVGL apps on CM4

I will close this issue for now, but will let yo know if I manage to get compiled version,...

**Comment by goran-mahovlic** [comment]
>>  Well, if I understand correctly, you are not able to link the SDL library, right?

Yes, that is correct

>> Copy SDL/ directory to your project directory

I am just using your project - I have build SDL and make a copy of that aarch64 build to project/SDL2 directory

>> Add the references to SDL into you build system (last step)

Your Makefile already have those references but it still complains about not able to find SDL

![Screenshot from 2023-11-28 13-50-48](https://github.com/JON95Git/lvgl-rasp-sdl/assets/4248736/f139af2e-3a49-4336-ba04-801eb64c5b1b)

**Comment by JON95Git** [comment]
Hi @goran-mahovlic.
I just tried here on another machine and had some issues too:
![image](https://github.com/JON95Git/lvgl-rasp-sdl/assets/23710201/42ccf846-1e22-43f2-8c1a-0e9facfaff0a)

I noticed some missing libraries on Makefile: ` -ldl -lpthread`

So, I updted the Makefile and used the exact same toolchain I used before (old toolchain I have on my personal computer): https://drive.google.com/drive/folders/1AiPD9IrispEGXqNN2Vi52IL4D89y3DF-?usp=sharing

It worked:

![image](https://github.com/JON95Git/lvgl-rasp-sdl/assets/23710201/b7532728-3a0b-4dda-9ff8-53454a13bab5)

**Comment by goran-mahovlic** [comment]
But are you using SDL1 or SDL2 - in instructions there is SDL1 link - SDL-1.2.15.tar.gz

**Comment by JON95Git** [comment]
I used SDL2 (I don't remember exactly which version, it's my fault for not documenting this)
The instructions mention SDL1 because of the Raspberry Pi forum post which is relatively old.

**Comment by goran-mahovlic** [comment]
> I used SDL2 (I don't remember exactly which version, it's my fault for not documenting this) The instructions mention SDL1 because of the Raspberry Pi forum post which is relatively old.

Tnx, I am building SDL2 on rasp - so I will check if this will work

**Comment by goran-mahovlic** [comment]
I have used this version http://www.libsdl.org/release/SDL2-2.0.14.tar.gz

used this on first error

sed -i '/_XData32/d' src/video/x11/SDL_x11sym.h

And applied this patch 

https://741490.bugs.gentoo.org/attachment.cgi?id=670840

After that SDL2 compiles, and your project compiles - click is not recognized but that is probably some other problem  

![Screenshot from 2023-11-28 21-26-13](https://github.com/JON95Git/lvgl-rasp-sdl/assets/4248736/732ef37a-3eb7-42b5-9b97-d20315a622cf)

**Comment by JON95Git** [comment]
Nice to see it worked.
To enable the mouse pointer as a valid input you need to change some configurations on the example code.
I think only the touch sensor is enabled in the code, not sure.

**Comment by goran-mahovlic** [comment]
Cool I will check/add mouser later 

Here is my fork where I will continue working on CM4 version - I have added some changes to README as it already have right SDL2 libraries. 

Now I need to remake it to support envox studio builder and eez-framework

**Comment by JON95Git** [comment]
Great. Glad to know my work here helped someone.
I'll close the issue for now.
Feel free to reopen it or create another issue.

**Comment by goran-mahovlic** [comment]
Just an info:

Envox managed to create similar thing but with new LVGL - and it can be now used with EEZ Studio so I have used that one...

https://github.com/eez-open/lvgl-sdl-demo

https://www.envox.eu/studio/studio-introduction/

My article about progress HW: https://intergalaktik.eu/news/bb3-cm4-pcb
